
name: CICD

on:
  push:
    branches: [ main, dev, ps-feature*, feature* ]
  pull_request:
    branches: [ main, dev, ps-feature*, feature* ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install test dependencies
      run: |
        npm install
        npm install -g pm2
    - name: Install Chrome
      run: |
        wget --no-verbose https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
    - name: Daemonize node app
      run: pm2 start ./backend/index.js --name our-webshop
    - name: Run REST API tests
      run: npm run test-rest
    - name: Run BDD tests
      run: HEADLESS_CHROME=yes WDIO_LOG_LEVEL=warn npm run test-bdd
    - name: Run unit tests
      run: npm run test-unit
  check-env:
    name: Check if a host for deployment is defined
    outputs:
      dev-host-defined: ${{ steps.dev-host-defined.outputs.defined }}
    steps:
    - id: dev-host-defined
      env:
        DEV_SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
      if: "${{ env.DEV_SSH_HOST != '' }}"
      run: echo "::set-output name=defined::true"
  deploy_dev:
    needs: [ test, check-env ]
    if: github.ref == 'refs/heads/dev'
    if: needs.check-env.outputs.dev-host-defined == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH
      env:
        DEV_SSH_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
        DEV_SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
        DEV_SSH_USER: ${{ secrets.DEV_SSH_USER }}
        DEV_SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEV_SSH_KEY" > ~/.ssh/dev.key
        chmod 600 ~/.ssh/dev.key
        cat >>~/.ssh/config <<_EOF_
        Host dev
          HostName $DEV_SSH_HOST
          User $DEV_SSH_USER
          Port $DEV_SSH_PORT
          IdentityFile ~/.ssh/dev.key
          StrictHostKeyChecking no
        _EOF_
    - name: Prepare app dirs
      run: |
        ssh dev 'mkdir -p ~/our-webshop/{app,log}'
        rsync -vaR -e 'ssh' package.json backend/*.js backend/*.json frontend/* dev:~/our-webshop/app/
        rsync -vaR -e 'ssh' --ignore-existing backend/database/webshop.db dev:~/our-webshop/app/
    - name: Install dependencies and start the app
      run: ssh dev 'cd ~/our-webshop/app && npm install && { pm2 start backend --name our-webshop --log ../log/app.log --time || pm2 restart our-webshop; }'
